apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: webapp:1.0
        name: webapp
