apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-svc
  name: webapp-svc
spec:
  ports:
  - name: 3000-80
    port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp-svc
  type: NodePort