apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: webapp
spec:
  ports:
  - name: 3000-80
    port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: LoadBalancer
